services:
  web:
    # build: 
    #   context: .
    #   dockerfile: ./docker/Dockerfile.frontend
    image: terminalwarlord/tic-tac-toe-frontend:latest
    ports:
      - "5001:3000"
    
  
  websocket:
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile.ws
    image: terminalwarlord/tic-tac-toe-ws:latest
    ports:
      - "8080:8080"
    
  # nginx:
  #     image: nginx:latest
  #     ports:
  #       - "5001:80"
  #       - "8080:443"
  #     volumes:
  #       - ./nginx/conf:/etc/nginx/conf.d
  #       - ./certbot/www:/var/www/certbot
  #       - ./certbot/conf:/etc/letsencrypt
  #     depends_on:
  #       - web
  #       - websocket

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   command: renew