services:
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    
  
  websocket:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ws
    ports:
      - "8080:8080"
    