name: Deploy Frontend to VM
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: terminalwarlord/tic-tac-toe-frontend:${{github.sha}}

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Login to VPS and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 -i ~/.ssh/id_rsa ${{ secrets.USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            mkdir -p ~/${{ secrets.DIRECTORY }}
            cd ~/${{ secrets.DIRECTORY }}

            # Remove existing container
            if [ $(docker ps -q -f name=tic-tac-toe-frontend) ]; then
              docker stop tic-tac-toe-frontend
            fi

            # Run new container
            docker run --rm -p 5001:3000 terminalwarlord/tic-tac-toe-frontend:${{ github.sha }}
          EOF

